rails/Poke/config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  resources :attacks

  root 'pokemons#index'

end

rails/Poke/app/models/ability.rb
class Ability < ActiveRecord::Base
end

rails/Poke/app/models/attack.rb
class Attack < ActiveRecord::Base
	def details
		AttackDetails.find_by_attack_code(self.code)
	end
	
	def attack_code
		details.attack_code
	end
	
	def accuracy
		details.accuracy
	end
	
	def category_code
		details.category_code
	end
	
	def caused_effect
		details.caused_effect
	end
	
	def crit_rate
		details.crit_rate
	end
	
	def damage_class
		details.damage_class
	end
	
	def effect_chance
		details.effect_chance
	end
	
	def flinch_chance
		details.flinch_chance
	end
	
	def healing
		details.healing
	end
	
	def max_turns
		details.max_turns
	end
	
	def min_turns
		details.min_turns
	end
	
	def power
		details.power
	end
	
	def pp
		details.pp
	end
	
	def priority
		details.priority
	end
	
	def recoil
		details.recoil
	end
	
	def status
		details.status
	end
	
	def attack_type
		details.pokemon_type_code
	end
end

rails/Poke/app/models/attack_details.rb
class AttackDetails < ActiveRecord::Base
	belongs_to :attack
end

rails/Poke/app/models/berry.rb
class Berry < Item
end

rails/Poke/app/models/category.rb
class Category < ActiveRecord::Base
end

rails/Poke/app/models/egg_group.rb
class EggGroup < ActiveRecord::Base
end

rails/Poke/app/models/evolution.rb
class Evolution < ActiveRecord::Base
end

rails/Poke/app/models/gen.rb
class Gen < ActiveRecord::Base
end

rails/Poke/app/models/item.rb
class Item < ActiveRecord::Base
end

rails/Poke/app/models/nature.rb
class Nature < ActiveRecord::Base
end

rails/Poke/app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
	default_scope { order(dex_number: :asc, form: :asc) }
	
	belongs_to :pokemon_name
	has_many :pokemon_attacks
	has_many :attack_codes, through: :pokemon_attacks, source: "attack"
	
	def name
		pokemon_name.name
	end
	
	def attacks
		result = []
		self.attack_codes.each do |att|
			result << att.code
		end
		result
	end
	
	def abilities
		[self.ability_1, self.ability_2, self.ability_3]
	end
	
	def baseStats
		[self.base_hp, self.base_attack, self.base_defense, self.base_sp_attack, self.base_sp_defense, self.base_speed]
	end
	
	def types
		[self.type_1, self.type_2]
	end
end

rails/Poke/app/models/pokemon_attack.rb
class PokemonAttack < ActiveRecord::Base
	belongs_to :pokemon
	belongs_to :attack
end

rails/Poke/app/models/pokemon_name.rb
class PokemonName < ActiveRecord::Base
end

rails/Poke/app/models/pokemon_type.rb
class PokemonType < ActiveRecord::Base
end

rails/Poke/app/models/version.rb
class Version < ActiveRecord::Base
end

rails/Poke/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/Poke/app/controllers/attacks_controller.rb
class AttacksController < ApplicationController
	before_action :set_attack, only: [:show, :edit, :update, :destroy]
	
	def index
		
	end
	
	def show
	end
	
	def edit
	end
	
	def update
	end
	
	def destroy
	end
	
	private
		def set_attack
			@attack = Attack.find_by_code(params[:id])
		end
end

rails/Poke/app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
	before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

	# GET /pokemons
	# GET /pokemons.json
	def index
		@pokemons = Pokemon.all
	end

	# GET /pokemons/1
	# GET /pokemons/1.json
	def show
	end

	# GET /pokemons/new
	def new
		@pokemon = Pokemon.new
	end

	# GET /pokemons/1/edit
	def edit
	end

	# POST /pokemons
	# POST /pokemons.json
	def create
		@pokemon = Pokemon.new(pokemon_params)

		respond_to do |format|
			if @pokemon.save
			format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
			format.json { render :show, status: :created, location: @pokemon }
			else
			format.html { render :new }
			format.json { render json: @pokemon.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /pokemons/1
	# PATCH/PUT /pokemons/1.json
	def update
		respond_to do |format|
			if @pokemon.update(pokemon_params)
			format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
			format.json { render :show, status: :ok, location: @pokemon }
			else
			format.html { render :edit }
			format.json { render json: @pokemon.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /pokemons/1
	# DELETE /pokemons/1.json
	def destroy
		@pokemon.destroy
		respond_to do |format|
			format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_pokemon
			form = (params[:form]) ? params[:form] : 0
			@pokemon = Pokemon.where(dex_number: params[:id], form: form).first
			@all_forms = Pokemon.where(dex_number: params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def pokemon_params
			params.require(:pokemon).permit(:dex_number, :form, :egg_group_1, :egg_group_2, :evolution, :height, :pokemon_name_id, :weight, :ability_1, :ability_2, :ability_3, :min_level, :base_hp, :base_attack, :base_defense, :base_sp_attack, :base_sp_defense, :base_speed, :type_1, :type_2)
		end
end

rails/Poke/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/Poke/app/helpers/attacks_helper.rb
module AttacksHelper
end

rails/Poke/app/helpers/pokemons_helper.rb
module PokemonsHelper
end

rails/Poke/app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dex_number %><br>
    <%= f.number_field :dex_number %>
  </div>
  <div class="field">
    <%= f.label :form %><br>
    <%= f.number_field :form %>
  </div>
  <div class="field">
    <%= f.label :egg_group_1 %><br>
    <%= f.number_field :egg_group_1 %>
  </div>
  <div class="field">
    <%= f.label :egg_group_2 %><br>
    <%= f.number_field :egg_group_2 %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :pokemon_name_id %><br>
    <%= f.number_field :pokemon_name_id %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :ability_1 %><br>
    <%= f.number_field :ability_1 %>
  </div>
  <div class="field">
    <%= f.label :ability_2 %><br>
    <%= f.number_field :ability_2 %>
  </div>
  <div class="field">
    <%= f.label :ability_3 %><br>
    <%= f.number_field :ability_3 %>
  </div>
  <div class="field">
    <%= f.label :min_level %><br>
    <%= f.number_field :min_level %>
  </div>
  <div class="field">
    <%= f.label :base_hp %><br>
    <%= f.number_field :base_hp %>
  </div>
  <div class="field">
    <%= f.label :base_attack %><br>
    <%= f.number_field :base_attack %>
  </div>
  <div class="field">
    <%= f.label :base_defense %><br>
    <%= f.number_field :base_defense %>
  </div>
  <div class="field">
    <%= f.label :base_sp_attack %><br>
    <%= f.number_field :base_sp_attack %>
  </div>
  <div class="field">
    <%= f.label :base_sp_defense %><br>
    <%= f.number_field :base_sp_defense %>
  </div>
  <div class="field">
    <%= f.label :base_speed %><br>
    <%= f.number_field :base_speed %>
  </div>
  <div class="field">
    <%= f.label :type_1 %><br>
    <%= f.number_field :type_1 %>
  </div>
  <div class="field">
    <%= f.label :type_2 %><br>
    <%= f.number_field :type_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/Poke/app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

rails/Poke/app/views/pokemons/index.html.erb
<h1>Listing pokemons</h1>

<table>
	<thead>
		<tr>
			<th>Dex number</th>
			<th>Form</th>
			<th>Egg group 1</th>
			<th>Egg group 2</th>
			<th>Height</th>
			<th>Pokemon name</th>
			<th>Weight</th>
			<th>Ability 1</th>
			<th>Ability 2</th>
			<th>Ability 3</th>
			<th>Min level</th>
			<th>Base hp</th>
			<th>Base attack</th>
			<th>Base defense</th>
			<th>Base sp attack</th>
			<th>Base sp defense</th>
			<th>Base speed</th>
			<th>Type 1</th>
			<th>Type 2</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @pokemons.each do |pokemon| %>
			<tr>
				<td><%= pokemon.dex_number %></td>
				<td><%= pokemon.form %></td>
				<td><%= EggGroup.find(pokemon.egg_group_1).name if pokemon.egg_group_1 %></td>
				<td><%= EggGroup.find(pokemon.egg_group_2).name if pokemon.egg_group_2 %></td>
				<td><%= pokemon.height %></td>
				<td><%= pokemon.pokemon_name.name %></td>
				<td><%= pokemon.weight %></td>
				<td><%= Ability.find_by_code(pokemon.ability_1).name unless pokemon.ability_1.nil?%></td>
				<td><%= Ability.find_by_code(pokemon.ability_2).name unless pokemon.ability_2.nil? %></td>
				<td><%= Ability.find_by_code(pokemon.ability_3).name unless pokemon.ability_3.nil? %></td>
				<td><%= pokemon.min_level %></td>
				<td><%= pokemon.base_hp %></td>
				<td><%= pokemon.base_attack %></td>
				<td><%= pokemon.base_defense %></td>
				<td><%= pokemon.base_sp_attack %></td>
				<td><%= pokemon.base_sp_defense %></td>
				<td><%= pokemon.base_speed %></td>
				<td><%= PokemonType.find_by_code(pokemon.type_1).name unless pokemon.type_1.nil?%></td>
				<td><%= PokemonType.find_by_code(pokemon.type_2).name unless pokemon.type_2.nil? %></td>
				<% if pokemon.form > 0 %>
					<td><%= link_to 'Show', pokemon_path(pokemon.dex_number, form: pokemon.form ) %></td>
				<% else %>
					<td><%= link_to 'Show', pokemon_path(pokemon.dex_number) %></td>
				<% end %>
				<td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
				<td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

rails/Poke/app/views/pokemons/new.html.erb
<h1>New pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

rails/Poke/app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dex number:</strong>
  <%= @pokemon.dex_number %>
</p>

<p>
  <strong>Form:</strong>
  <%= @pokemon.form %>
</p>

<p>
  <strong>Egg group 1:</strong>
  <%= @pokemon.egg_group_1 %>
</p>

<p>
  <strong>Egg group 2:</strong>
  <%= @pokemon.egg_group_2 %>
</p>

<p>
  <strong>Height:</strong>
  <%= @pokemon.height %>
</p>

<p>
  <strong>Pokemon name:</strong>
  <%= @pokemon.pokemon_name.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pokemon.weight %>
</p>

<p>
  <strong>Ability 1:</strong>
  <%= @pokemon.ability_1 %>
</p>

<p>
  <strong>Ability 2:</strong>
  <%= @pokemon.ability_2 %>
</p>

<p>
  <strong>Ability 3:</strong>
  <%= @pokemon.ability_3 %>
</p>

<p>
  <strong>Min level:</strong>
  <%= @pokemon.min_level %>
</p>

<p>
  <strong>Base hp:</strong>
  <%= @pokemon.base_hp %>
</p>

<p>
  <strong>Base attack:</strong>
  <%= @pokemon.base_attack %>
</p>

<p>
  <strong>Base defense:</strong>
  <%= @pokemon.base_defense %>
</p>

<p>
  <strong>Base sp attack:</strong>
  <%= @pokemon.base_sp_attack %>
</p>

<p>
  <strong>Base sp defense:</strong>
  <%= @pokemon.base_sp_defense %>
</p>

<p>
  <strong>Base speed:</strong>
  <%= @pokemon.base_speed %>
</p>

<p>
  <strong>Type 1:</strong>
  <%= @pokemon.type_1 %>
</p>

<p>
  <strong>Type 2:</strong>
  <%= @pokemon.type_2 %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>